compatibility_date = "2024-10-02"
[vars]
 DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYmNhMzYxZGItNTA4Ni00MDQ2LWJmNGQtNDFhOTg5MmE2YTU5IiwidGVuYW50X2lkIjoiYmQ4MTk5ZDZjNmMwZWJiMzBiYjk1ZTNiOGZjNTc4OWM1NjVhN2RiYzkzNGJlMGQ5ODA1NmM0MmUyN2Y3Y2Q3NyIsImludGVybmFsX3NlY3JldCI6IjA2NzcyNWQ4LTgxYWEtNDM1Yy05ZThmLWM4ZmRiODc5YjBiNSJ9.zYMsurjK4RyjQ3hjakMRRBUxceveXqP20NHXLWKARiw"
 JWT_SECRET = "saiyam1secret"